<?php

namespace app\controllers;

use app\components\payment_gateway\MerchantSandbox;
use app\components\payment_gateway\Tripay;
use app\models\Invoice;
use app\models\User;
use Yii;
use yii\helpers\Json;

class TripayController extends \yii\web\Controller
{
    public function actionIndex()
    {
        $merchant = MerchantSandbox::get();
        $callbackSignature = \Yii::$app->request->get('HTTP_X_CALLBACK_SIGNATURE');
        $json = Json::encode(\Yii::$app->request->getRawBody());

        $signature = hash_hmac('sha256', $json, $merchant['private_key']);
        if ($signature !== (string) $callbackSignature) {
            return Json::encode([
                'success' => false,
                'message' => 'Invalid signature',
            ]);
        }

        if ('payment_status' !== (string) \Yii::$app->request->get('HTTP_X_CALLBACK_SIGNATURE')) {
            return Json::encode([
                'success' => false,
                'message' => 'Invalid callback event, no action was taken',
            ]);
        }

        $data = Json::decode($json);

        $uniqueRef = $data->merchant_ref;
        $status = strtoupper((string) $data->status);

        if (1 === (int) $data->is_closed_payment) {
            $invoice = Invoice::findOne([
                'code' => $uniqueRef,
                'status' => Tripay::STATUS_UNPAID
            ]);

            if ($invoice == null) {
                return Json::encode([
                    'success' => false,
                    'message' => 'No invoice found or already paid: ' . $uniqueRef,
                ]);
            }

            /** update Invoice*/

            $userTripay = User::getUserTripay();
            $now = date('Y-m-d H:i:s');
            $statusValue = Tripay::getListStatusPayment()[$status];
            $invoice->updateAttributes([
                'status' => $statusValue,
                'approved_by' => $userTripay->id,
                'approved_date' => $now
            ]);

            /** update deposit */
            $deposit = $invoice->deposit;
            $deposit->updateAttributes([
                'status' => 1
            ]);

            return Json::encode([
                'success' => true
            ]);
        }
    }

    public function actionTest()
    {
        return Json::encode([
            'success' => true
        ]);
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation=false;
        if ($action->id == 'writeSession') {
            Yii::$app->controller->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    public function afterAction($action, $result)
    {
        $this->enableCsrfValidation=true;
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

}
