<?php

namespace app\widgets;

use Yii;
use yii\bootstrap5\Html;

/**@var $title string|null */

class Breadcrumbs extends \yii\bootstrap5\Breadcrumbs
{
    public $title;

    private function templateOpen()
    {
        return '<div class="row"><div class="col-12"><div class="page-title-box"><div class="page-title-right">';
    }

    private function templateClose()
    {
        return '</div><h4 class="page-title">'.$this->title.'</h4></div></div></div>';
    }

    public function run(): string
    {
        if (!isset($this->options['id'])) {
            $this->options['id'] = "{$this->getId()}-breadcrumb";
        }

        /** @psalm-suppress InvalidArgument */
        Html::addCssClass($this->options, ['widget' => 'breadcrumb']);

        if (empty($this->links)) {
            return '';
        }

        $links = [];

        if ($this->homeLink === []) {
            $links[] = $this->renderItem([
                'label' => Yii::t('yii/bootstrap5', 'Home'),
                'url' => Yii::$app->homeUrl,
            ], $this->itemTemplate);
        } elseif ($this->homeLink !== false) {
            $links[] = $this->renderItem($this->homeLink, $this->itemTemplate);
        }

        foreach ($this->links as $link) {
            if (!is_array($link)) {
                $link = ['label' => $link];
            }

            $links[] = $this->renderItem($link, isset($link['url']) ? $this->itemTemplate : $this->activeItemTemplate);
        }

        $return = $this->templateOpen();
        $return .= Html::tag($this->tag, implode('', $links), $this->options);
        $return .= $this->templateClose();
        return $return;
    }

    public function render($view, $params = [])
    {
        return parent::render($view, $params); // TODO: Change the autogenerated stub
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (@$this->options['title'] != null) {
            $this->title = $this->options['title'];
        }
    }
}